[project]
name = "test_pixi"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "*"

#******************************* GPU ********************************#
[feature.gpu]
channels = ["nvidia", "conda-forge", "pytorch"]
system-requirements = { cuda = "11.8" }

[feature.gpu.dependencies]
pytorch = { version = "~=2.3.0", channel = "pytorch" }
pytorch-cuda = { version = "11.8", channel = "pytorch" }

[environments]
gpu = { features = ["gpu"]}
