[project]
name = "b3d-prototype"
version = "0.1.0"
description = "Add a short description here"
authors = [{name = "Aaron Steele", email = "eightysteele@gmail.com"}]
requires-python = ">= 3.11"
dependencies = ["genjax==0.5.0.post13.dev0+973fb60d", "pyransac3d>=0.6.0,<0.7", "opencv-python>=4.10.0.84,<4.10.1", "torch>=2.3.1,<2.4", "torchaudio>=2.3.1,<2.4", "torchvision>=0.18.1,<0.19", "pyliblzfse>=0.4.1,<0.5"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-options]
index-url = "https://pypi.org/simple"
extra-index-urls = ["https://oauth2accesstoken@us-west1-python.pkg.dev/probcomp-caliban/probcomp/simple"]

[tool.pixi.pypi-dependencies]
b3d = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
mesalib = ">=24.1.3,<24.2"
mesa-libegl-devel-cos7-x86_64 = "*"
glfw = "*"
mesa-libgl-devel-cos7-x86_64 = "*"
mesa-libglu-devel-cos7-x86_64 = "*"
ffmpeg = "*"
python = "3.12"
rerun-sdk = "==0.16.1"
tqdm = "==4.66.2"
numpy = "==1.26.4"
pillow = "==10.3.0"
trimesh = ">=4.4.3,<4.5"
matplotlib = ">=3.9.1,<3.10"
scipy = ">=1.14.0,<1.15"
ninja = ">=1.12.1,<1.13"
jupyter = ">=1.0.0,<1.1"
pdoc3 = ">=0.11.1,<0.12"
optax = ">=0.2.2,<0.3"
fire = ">=0.6.0,<0.7"
natsort = ">=8.4.0,<8.5"
distinctipy = ">=1.3.4,<1.4"
scikit-learn = ">=1.5.1,<1.6"
ipython = ">=8.26.0,<8.27"

[tool.pixi.feature.cuda]
system-requirements = { cuda = "12" }

[tool.pixi.feature.cuda.dependencies]
jax = ">=0.4.28"
jaxlib = { version = ">=0.4.28", build = "cuda12*" }
cuda-nvcc = ">=12.5.82,<12.6"
libnvjitlink = ">=12.5.82,<12.6"

[tool.pixi.feature.cuda.tasks]
rerun = "rerun --port 8812"
b3d-pull = {cmd = "python b3d_pull.py -ow", cwd = "b3d/bucket_utils" }

[tool.pixi.feature.test.dependencies]
pytest = "*"

[tool.pixi.feature.test.tasks]
test = "pytest tests"

[tool.pixi.environments]
cuda = {features = ["cuda", "test"], solve-group = "cuda"}


