[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "jax_gl_renderer"
version = "0.1.1"

[tool.setuptools.packages.find]
include = ["jax_gl_renderer"]
namespaces = false